version: '3.3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
    hostname: zookeeper
    volumes:
      - /home/azureuser/zookeeper/data:/opt/zookeeper-3.4.13/data
  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_CREATE_TOPICS: "events:1:1"
      KAFKA_ADVERTISED_HOST_NAME: kafka-acit3855.eastus.cloudapp.azure.com
      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://kafka-acit3855.eastus.cloudapp.azure.com:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/kafka-logs
      KAFKA_BROKER_ID: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/azureuser/kafka:/kafka/kafka-logs
    depends_on:
      - "zookeeper"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  receiver:
    image: receiver  # Default to using the prebuilt image named 'receiver'
    build:
      context: ../receiver  # Build context for creating the image if '--build' is used
    ports:
      - "8080:8080"
    environment:
      - TARGET_ENV=test
    volumes:
      - /home/azureuser/config/receiver:/config
      - /home/azureuser/logs:/logs
    depends_on:
      kafka:
        condition: service_healthy
      db:
        condition: service_started

  storage:
    image: storage
    build:
      context: ../storage
    ports:
      - "8090:8090"
    environment:
      - TARGET_ENV=test
    volumes:
      - /home/azureuser/config/storage:/config
      - /home/azureuser/logs:/logs
    depends_on:
      kafka:
        condition: service_healthy
      db:
        condition: service_started


  anomaly:
    image: anomaly
    build:
      context: ../anomaly
    ports:
      - "8120:8120"
    environment:
      - TARGET_ENV=test
    volumes:
      - /home/azureuser/config/anomaly:/config
      - /home/azureuser/logs:/logs
    depends_on:
      kafka:
        condition: service_healthy
      db:
        condition: service_started


  processing:
    image: processing
    build:
      context: ../processor
    ports:
      - "8100:8100"
    environment:
      - TARGET_ENV=test
    volumes:
      - /home/azureuser/config/processing:/config
      - /home/azureuser/logs:/logs
      - processing-db:/data
    depends_on:
      - kafka
      - db
      - storage
      - receiver

  analyzer:
    image: analyzer
    build:
      context: ../analyzer
    ports:
      - "8110:8110"
    environment:
      - TARGET_ENV=test
    volumes:
      - /home/azureuser/config/analyzer:/config
      - /home/azureuser/logs:/logs
    depends_on:
      - kafka
      - db
      - storage
      - receiver
  
  backend:
    image: backend
    build:
      context: ../dashboard/backend  # Path to the directory where your Dockerfile is located
    ports:
      - "3000:3000"
    depends_on:
      - kafka
      - db
      - receiver
      - storage
      - processing
      - analyzer


  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'events'
      MYSQL_USER: 'SIan'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
volumes:
  my-db:
  processing-db: