openapi: 3.0.0
info:
  title: DungeonFindr API
  description: This API helps organize D&D Games
  contact:
    email: istewart17@my.bcit.ca
  version: 0.0.2
servers:
- url: /
tags:
- name: formation
  description: Operations used to form a party of players
paths:

  /health: 
    get:
      summary: gets the event stats
      operationId: app.get_health
      description: Gets the stats of the history events 
      responses:
        '200':
          description: Successfully returned a heart rate event 
          content:
            application/json: 
              schema:
                required:
                  - receiver_status
                  - storage_status
                  - analyzer_status
                type: object
                properties:
                  receiver_status:
                    type: string
                  storage_status:
                    type: string
                  analyzer_status:
                    type: string
              


